--------------- SALES AND MARKETING MANAGER ------------------------
----1)		
--CREATE TRIGGER CALCULATE_T_PRICE
--BEFORE INSERT ON SALES
--REFERENCING NEW AS N
--FOR EACH ROW 
--MODE DB2SQL
    --SET TOTAL_PRICE = (SELECT PS.CAR_PRICE * N.QTY
                      --FROM CAR PS
		--WHERE N.CAR_ID = PS.CAR_ID);


------2) WORKING
--CREATE VIEW TOP_CAR_SALES AS
--SELECT * FROM (SELECT CAR_MODEL, SUM(QTY) AS TOTALQTYSOLD, SUM(CAR_PRICE) AS TOTAL_INCOME
--FROM SALES S, CAR C
--WHERE S.CAR_ID = C.CAR_ID
--GROUP BY CAR_MODEL
--ORDER BY TOTALQTYSOLD DESC);


--3) WORKING
CREATE FUNCTION MONTHLY_TOTAL_SALES(MONTH INT)
RETURNS TABLE (TOTAL_MONTH_SALES DECIMAL(10,2))
LANGUAGE SQL
READS SQL DATA
NO EXTERNAL ACTION
DETERMINISTIC
RETURN SELECT (SELECT SUM(TOTAL_PRICE) 
	FROM SALES S, TIME T
	WHERE S.TIME_ID = T.TIME_ID)
AS GRAND_TOTAL FROM
SYSIBM.SYSDUMMY1;

---- TO CALL THIS FUNCTION [db2 " SELECT * FROM  TABLE(MONTHLY_TOTAL_SALES(1)) AS MANTHLY"]

-------------------------- BRANCH MANAGER --------------------------------
----4)WORKING
--CREATE VIEW TOP_BRANCH_SALES AS
--SELECT * FROM (SELECT SALES.BR_ID, SUM(TOTAL_PRICE) AS TOTAL_EACH_BRANCH, 
--SUM(QTY) AS QTY_SOLD
--FROM SALES
--GROUP BY BR_ID
--ORDER BY TOTAL_EACH_BRANCH DESC);



----5)TAK
------ALTER TABLE BRANCH ADD COLUMN BR_STATUS VARCHAR(15);

--CREATE PROCEDURE ADD_STATUS
--(IN ID CHAR(3) )
--IF (SELECT SUM(QTY) FROM SALES WHERE SALES.BR_ID = ID)=0
--THEN UPDATE BRANCH SET BR_STATUS = 'VERY BAD'
--WHERE BRANCH.BR_ID = ID;

--ELSEIF
--(
--SELECT SUM(QTY)
--FROM SALES WHERE SALES.BR_ID = ID) BETWEEN 1 AND 10
--THEN UPDATE BRANCH SET BR_STATUS = 'SATISFIED'
--WHERE BRANCH.BR_ID = ID;

--ELSEIF (SELECT SUM(QTY) FROM SALES WHERE SALES.BR_ID = ID) BETWEEN 21 AND 30
--THEN UPDATE BRANCH SET BR_STATUS = 'GOOD'
--WHERE BRANCH.BR_ID = ID;

--ELSEIF (SELECT SUM(QTY) FROM SALES WHERE SALES.BR_ID = ID) BETWEEN 31 AND 60
--THEN UPDATE BRANCH SET BR_STATUS = 'VERY GOOD'
--WHERE BRANCH.BR_ID = ID;

--ELSEIF (SELECT SUM(QTY) FROM SALES WHERE SALES.BR_ID = ID) > 60
--THEN UPDATE BRANCH SET BR_STATUS = 'EXCELLENT '
--WHERE BRANCH.BR_ID = ID;

--END IF@																

----6) WORKING
--CREATE VIEW TOTAL_SOLD AS
--SELECT	(SELECT SUM(TOTAL_PRICE)
	--FROM SALES, BRANCH
	--WHERE BRANCH.BR_ID = SALES.BR_ID) 
--AS TOTAL_SOLD FROM
--SYSIBM.SYSDUMMY1;

------------------------ CUSTOMER RELATIONSHIP MANAGER -------------------
----7) WORKING
--CREATE VIEW BESTPRODUCTCUSTOMER AS
--SELECT * FROM (SELECT CU_FNAME , SUM(QTY) AS TOTAL_ORDER_NUMBER
--FROM SALES S, CUSTOMER C
--WHERE S.CU_ID=C.CU_ID
--GROUP BY CU_FNAME
--ORDER BY TOTAL_ORDER_NUMBER DESC);


----8)

--CREATE FUNCTION MONTHLY_TOTAL_SALES_BY_BRANCH(MONTH INT, BRANCH CHAR(3))
--RETURNS TABLE (TOTAL_MONTH_SALES_BY_BRANCH DECIMAL(10,2))
--LANGUAGE SQL
--READS SQL DATA
--NO EXTERNAL ACTION
--DETERMINISTIC
--RETURN SELECT (SELECT SUM(TOTAL_PRICE) 
	--FROM SALES S, TIME T
	--WHERE S.TIME_ID = T.TIME_ID
	  --AND S.BR_ID = BRANCH
	 --AND T.MONTHNUMBER = MONTH)
--AS GRAND_TOTAL FROM
--SYSIBM.SYSDUMMY1;






