--CREATE DATABASE DDL;
--CONNECT TO DDL;


--DROP TABLE BRANCH;
--DROP TABLE CAR;
--DROP TABLE MANUFACTURER;
--DROP TABLE CUSTOMER;
--DROP TABLE TIME;
--DROP TABLE SALES;

CREATE TABLE CAR (
        CAR_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 11111, INCREMENT BY 10), 
        CAR_MODEL VARCHAR(20),
        CAR_TYPE VARCHAR(20),
        CAR_YearOfManuf INT,
        CAR_PRICE DECIMAL(8,2),
        PRIMARY KEY (CAR_ID)
);
CREATE TABLE MANUFACTURER (
        MANU_ID CHAR(5) NOT NULL,
        MANU_NAME VARCHAR(15),
        MANU_COUNTRY VARCHAR(15),
        PRIMARY KEY (MANU_ID)
);
CREATE TABLE BRANCH (
        BR_ID CHAR(3) NOT NULL,
        BR_STATE VARCHAR(15),
        BR_CITY VARCHAR(15),
        BR_ZIPCODE VARCHAR(7),
        BR_STREET VARCHAR(20),
        PRIMARY KEY (BR_ID)
);
CREATE TABLE CUSTOMER (
        CU_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        CU_FNAME VARCHAR(15),
        CU_LNAME VARCHAR(15),
        CU_GENDER CHAR(1) CHECK((CU_GENDER ='M') OR (CU_GENDER ='F')),
        CU_IncomePerYear VARCHAR(15), --DECIMAL(11,2)
        CU_PHONE INT,
        --CU_CURR CHAR(3) WITH DEFAULT 'USD',
        PRIMARY KEY (CU_ID)
);
CREATE TABLE TIME (
        TIME_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        TIME_YEAR INT WITH DEFAULT 2014,
        MonthNumber INT CHECK(MonthNumber <= 12),
        MonthName CHAR(10),
        DayNumber INT CHECK(DayNumber <= 31),
        HOLIDAY VARCHAR(30),
        PRIMARY KEY (TIME_ID)
);
CREATE TABLE SALES (
        BR_ID CHAR(3) NOT NULL,
        CAR_ID INT NOT NULL,
        MANU_ID CHAR(5) NOT NULL,
        CU_ID INT NOT NULL,
        TIME_ID INT NOT NULL,
        QTY INT WITH DEFAULT 1,
        TOTAL_PRICE DECIMAL(11,2) WITH DEFAULT 0,
        FOREIGN KEY (CAR_ID) REFERENCES CAR,
        FOREIGN KEY (MANU_ID) REFERENCES MANUFACTURER,
        FOREIGN KEY (BR_ID) REFERENCES BRANCH,
        FOREIGN KEY (CU_ID) REFERENCES CUSTOMER,
        FOREIGN KEY (TIME_ID) REFERENCES TIME,
        PRIMARY KEY (CAR_ID,MANU_ID,BR_ID,CU_ID,TIME_ID)
);
